[versions]
jackson = "2.18.2"
slf4j = "2.0.16"
errorprone = "2.36.0"
junit = "5.11.4"
soup = "1.18.3"

[libraries]
errorprone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone_core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "slf4j" }

soup = { module = 'org.jsoup:jsoup', version.ref = "soup" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
versions = "com.github.ben-manes.versions:0.52.0"
dependencycheck = "org.owasp.dependencycheck:8.4.3"
errorprone = "net.ltgt.errorprone:4.1.0"
